name: Docker Image CI

on: [push] 

env:
  IMAGE_NAME: unifi

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2

    - name: build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
    
    - name: log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: publish image
      run: |
        IMAGE_ID=ghcr.io/maehld/$IMAGE_NAME

        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
      
